default:
  tags:
    - devops-project

stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running Tests ...." && pwd && cd tests && pwd && go test -v ./... && cd ..

sonarqube:
  stage: sonarqube
  script:
    - cd api-gateway && sonar-scanner -Dsonar.projectKey=api-gateway -Dsonar.sources=. -Dsonar.host.url=http://localhost:9000 -Dsonar.login=squ_52c349d75d62086aeac4e1ae0e1b3a2a3b27f376


deploy:
  stage: deploy
  script:
    - docker-compose up -d
