default:
  tags:
    - devops-project

stages:
  - build
  - test
  - sonarqube
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running Tests ...." && pwd && cd tests && pwd && go test -v ./... && cd ..

sonarqube:
  stage: sonarqube
  script:
    - docker run --rm -e SONAR_HOST_URL="http://localhost:9000" -e SONAR_SCANNER_OPTS="-Dsonar.projectKey=api-gateway" -e SONAR_LOGIN="squ_52c349d75d62086aeac4e1ae0e1b3a2a3b27f376" -v "./api-gateway:/usr/src" sonarsource/sonar-scanner-cli


deploy:
  stage: deploy
  script:
    - docker-compose up -d
