default:
  tags:
    - devops-project

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - echo "Running Tests ...." && pwd && cd tests && pwd && go test ./... && cd ..

deploy:
  stage: deploy
  script:
    - docker-compose up -d
